### PR TITLE
Fix Repl missing readlink

### PR DESCRIPTION
**Pull request by GTrunSec**

### CODE REVIEW

**Comment by GTrunSec** [comment]
@blaggacao request a review, thx

**Comment by blaggacao** [comment]
Out of curiousity: On which platform does this occur? I sense it's a MacOS issue?

**Comment by GTrunSec** [comment]
platform: linux 

located: https://github.com/divnix/bud/blob/main/scripts/utils-repl/default.nix#L6

getting a flake.nix in out of the local dir as following:
```
bud repl <out of the local dir>
/nix/store/vjjpddjf4h9kn5va8adm4dai8s126j1v-repl: line 5: readlink: command not found
```

**Comment by blaggacao** [comment]
Thanks!

**Pull request merged**
